### PR TITLE
packages and setup updates

### PR DESCRIPTION
**Pull request by mstocchi**

### CODE REVIEW

**Comment by miguelcobain** [comment]
@mstocchi thank you for the PR. I don't use Hapi anymore.
I've added you as a collaborator. Feel free to take this boilerplate to new heights. :)

**Comment by mstocchi** [comment]
Thanks, it's really a good starting template so would be nice to keep updated.

**Comment by miguelcobain** [comment]
Btw, you like Ghost in the Shell? :)

**Comment by mstocchi** [comment]
Yes, somehow I ended using that as 'avatar' :)

**Pull request merged**
